swagger: '2.0'
info:
  version: '1.0'
  title: Object APIs
  description: 'TODO: Add Description'
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: example.com
basePath: /v1/object
securityDefinitions:
  auth:
    type: oauth2
    flow: implicit
    authorizationUrl: http://example.com/v1/object
    scopes: {}
    x-skip-client-authentication: false
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /update:
    post:
      description: ''
      summary: Update Object
      operationId: UpdatePost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/UpdateObjectrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: POST
          uri: /update
          headers:
            Content-Type: application/json
            Authorization: Bearer {{api-key}}
          body: >-
            {

            	"id": "",

                "ts": "",

                "params": { },

                "request":{

                    "entityName":"announcement",

            	    "indexed":true,

               	    "payload" : {

            	    	"id": "8e27cbf5-e299-43b0-bca7-8347f7e5abcf",

            			"userid":"8e27cbf5-e299-43b0-bca7",

            			"sourceid":"sourceId",

            			"details":{

            	  			"filename":"name"

            			},

            			"links":["asd","asdf"],

            			"attachments":["kjaslkdlk"],

            			"sentcount":1

            	    }

                }

            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Update Object
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /create:
    post:
      description: ''
      summary: Create Object
      operationId: CreatePost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/CreateObjectrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: POST
          uri: /create
          headers:
            Content-Type: application/json
            Authorization: Bearer {{api-key}}
          body: >-
            {

                "id": "",

                "ts": "",

                "params": { },

                "request":{

                    "entityName":"announcement",

                    "indexed":true,

                    "payload" : {

                    	"id": "8e27cbf5-e299-43b0-bca7-8347f7e5abcf",

                        "userid":"8e27cbf5-e299-43b0-bca7",

                        "sourceid":"sourceId",

                        "details":{

                			"filename":"name"

                		},

                		"links":["asd","asdf"],

                		"attachments":["kjaslkdlk"],

                		"sentcount":1

                    }

                }

            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Create Object
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /read/list:
    post:
      description: ''
      summary: List Objects
      operationId: ReadListPost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/ListObjectsrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: POST
          uri: /read/list
          headers:
            Content-Type: application/json
            Authorization: Bearer {{api-key}}
          body: >-
            {

              "id": "",

              "ts": "",

              "params": { },

              "request":{

                  "entityName":"announcement"

                }

            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: List Objects
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /read:
    post:
      description: ''
      summary: Read/Get Object
      operationId: ReadPost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/Read~1getObjectrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: POST
          uri: /read
          headers:
            Content-Type: application/json
            Authorization: Bearer {{api-key}}
          body: >-
            {

            	"id": "",

            	"ts": "",

            	"params": { },

                "request":{

                	"entityName":"announcement",

            		"id": "8e27cbf5-e299-43b0-bca7-8347f7e5abcf"

                }

            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Read/Get Object
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /metrics:
    post:
      description: ''
      summary: Metrics API
      operationId: MetricsPost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/MetricsApirequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: POST
          uri: /metrics
          headers:
            Content-Type: application/json
            Authorization: Bearer {{api-key}}
          body: >-
            {
              "id": "",
              "ts": "",
              "params": {},
              "request": {
                "entityName": "announcement",
                "rawQuery": {
                  "from": 0,
                  "size": 250,
                  "query": {
                    "bool": {
                      "must": [
                        {
                          "term": {
                            "batchId.raw": {
                              "value": "jkwf6t3r083fp4h",
                              "boost": 1
                            }
                          }
                        }
                      ],
                      "disable_coord": false,
                      "adjust_pure_negative": true,
                      "boost": 1
                    }
                  },
                  "_source": {
                    "includes": [
                      "userId",
                      "progress",
                      "enrolledDate",
                      "batchId",
                      "dateTime"
                    ],
                    "excludes": []
                  },
                  "aggs": {
                    "status": {
                      "terms": {
                        "field": "status.raw",
                        "include": [
                          "1",
                          "2",
                          "review"
                        ]
                      },
                      "aggs": {
                        "updated_on": {
                          "date_histogram": {
                            "field": "lastUpdatedOn",
                            "interval": "1d",
                            "format": "yyyy-MM-dd"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Metrics API
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /delete:
    post:
      description: ''
      summary: Delete Object
      operationId: DeletePost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/DeleteObjectrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: POST
          uri: /delete
          headers:
            Content-Type: application/json
            Authorization: Bearer {{api-key}}
          body: >-
            {

            	"id": "",

            	"ts": "",

            	"params": { },

                "request":{

                    "entityName":"announcement",

            		"indexed":"announcement",

            		"id": "8e27cbf5-e299-43b0-bca7-8347f7e5abcf"

                }

            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Delete Object
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /search:
    post:
      description: ''
      summary: Search Object
      operationId: SearchPost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/SearchObjectrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: POST
          uri: /search
          headers:
            Content-Type: application/json
            Authorization: Bearer {{api-key}}
          body: >-
            {

            	"id": "",

            	"ts": "",

            	"params": { },

                "request":{

                	"query": "ORG_TYPE",

            	    "entityName":"org_type",

            		"filters":{

            			"id":"98765432110"

            		},

            		"offset": 0,

            		"limit": 5

                }

            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Search Object
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
definitions:
  UpdateObjectrequest:
    title: Update ObjectRequest
    example:
      id: ''
      ts: ''
      params: {}
      request:
        entityName: announcement
        indexed: true
        payload:
          id: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
          userid: {{userId}}
          sourceid: sourceId
          details:
            filename: name
          links:
          - asd
          - asdf
          attachments:
          - kjaslkdlk
          sentcount: 1
    type: object
    properties:
      id:
        description: ''
        type: string
      ts:
        description: ''
        type: string
      params:
        description: ''
        example: {}
        type: object
      request:
        $ref: '#/definitions/Request'
        example:
          entityName: announcement
          indexed: true
          payload:
            id: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
            userid: {{userId}}
            sourceid: sourceId
            details:
              filename: name
            links:
            - asd
            - asdf
            attachments:
            - kjaslkdlk
            sentcount: 1
    required:
    - id
    - ts
    - params
    - request
  Request:
    title: Request
    example:
      entityName: announcement
      indexed: true
      payload:
        id: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
        userid: {{userId}}
        sourceid: sourceId
        details:
          filename: name
        links:
        - asd
        - asdf
        attachments:
        - kjaslkdlk
        sentcount: 1
    type: object
    properties:
      entityName:
        description: ''
        example: announcement
        type: string
      indexed:
        description: ''
        example: true
        type: boolean
      payload:
        $ref: '#/definitions/Payload'
        example:
          id: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
          userid: {{userId}}
          sourceid: sourceId
          details:
            filename: name
          links:
          - asd
          - asdf
          attachments:
          - kjaslkdlk
          sentcount: 1
    required:
    - entityName
    - indexed
    - payload
  Payload:
    title: Payload
    example:
      id: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
      userid: {{userId}}
      sourceid: sourceId
      details:
        filename: name
      links:
      - asd
      - asdf
      attachments:
      - kjaslkdlk
      sentcount: 1
    type: object
    properties:
      id:
        description: ''
        example: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
        type: string
      userid:
        description: ''
        example: 8e27cbf5-e299-43b0-bca743
        type: string
      sourceid:
        description: ''
        example: sourceId
        type: string
      details:
        $ref: '#/definitions/Details'
        example:
          filename: name
      links:
        description: ''
        example:
        - asd
        - asdf
        type: array
        items:
          type: string
      attachments:
        description: ''
        example:
        - kjaslkdlk
        type: array
        items:
          type: string
      sentcount:
        description: ''
        example: 1
        type: integer
        format: int32
    required:
    - id
    - userid
    - sourceid
    - details
    - links
    - attachments
    - sentcount
  Details:
    title: Details
    example:
      filename: name
    type: object
    properties:
      filename:
        description: ''
        example: name
        type: string
    required:
    - filename
  CreateObjectrequest:
    title: Create ObjectRequest
    example:
      id: ''
      ts: ''
      params: {}
      request:
        entityName: announcement
        indexed: true
        payload:
          id: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
          userid: 8e27cbf5-e2993-43b05-bca7322
          sourceid: sourceId
          details:
            filename: name
          links:
          - asd
          - asdf
          attachments:
          - kjaslkdlk
          sentcount: 1
    type: object
    properties:
      id:
        description: ''
        type: string
      ts:
        description: ''
        type: string
      params:
        description: ''
        example: {}
        type: object
      request:
        $ref: '#/definitions/Request'
        example:
          entityName: announcement
          indexed: true
          payload:
            id: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
            userid: 8e27cbf5-e299-43b04-bca755
            sourceid: sourceId
            details:
              filename: name
            links:
            - asd
            - asdf
            attachments:
            - kjaslkdlk
            sentcount: 1
    required:
    - id
    - ts
    - params
    - request
  ListObjectsrequest:
    title: List ObjectsRequest
    example:
      id: ''
      ts: ''
      params: {}
      request:
        entityName: announcement
    type: object
    properties:
      id:
        description: ''
        type: string
      ts:
        description: ''
        type: string
      params:
        description: ''
        example: {}
        type: object
      request:
        $ref: '#/definitions/Request9'
        example:
          entityName: announcement
    required:
    - id
    - ts
    - params
    - request
  Request9:
    title: Request9
    example:
      entityName: announcement
    type: object
    properties:
      entityName:
        description: ''
        example: announcement
        type: string
    required:
    - entityName
  Read/getObjectrequest:
    title: Read/Get ObjectRequest
    example:
      id: ''
      ts: ''
      params: {}
      request:
        entityName: announcement
        id: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
    type: object
    properties:
      id:
        description: ''
        type: string
      ts:
        description: ''
        type: string
      params:
        description: ''
        example: {}
        type: object
      request:
        $ref: '#/definitions/Request11'
        example:
          entityName: announcement
          id: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
    required:
    - id
    - ts
    - params
    - request
  Request11:
    title: Request11
    example:
      entityName: announcement
      id: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
    type: object
    properties:
      entityName:
        description: ''
        example: announcement
        type: string
      id:
        description: ''
        example: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
        type: string
    required:
    - entityName
    - id
  MetricsApirequest:
    title: Metrics APIRequest
    example:
      id: ''
      ts: ''
      params: {}
      request:
        entityName: announcement
        rawQuery:
          from: 0
          size: 250
          query:
            bool:
              must:
              - term:
                  batchId.raw:
                    value: jkwf6t3r083fp4h
                    boost: 1
              disable_coord: false
              adjust_pure_negative: true
              boost: 1
          _source:
            includes:
            - userId
            - progress
            - enrolledDate
            - batchId
            - dateTime
            excludes: []
          aggs:
            status:
              terms:
                field: status.raw
                include:
                - 1
                - 2
                - review
              aggs:
                updated_on:
                  date_histogram:
                    field: lastUpdatedOn
                    interval: 1d
                    format: yyyy-MM-dd
    type: object
    properties:
      id:
        description: ''
        type: string
      ts:
        description: ''
        type: string
      params:
        description: ''
        example: {}
        type: object
      request:
        $ref: '#/definitions/Request13'
        example:
          entityName: announcement
          rawQuery:
            from: 0
            size: 250
            query:
              bool:
                must:
                - term:
                    batchId.raw:
                      value: jkwf6t3r083fp4h
                      boost: 1
                disable_coord: false
                adjust_pure_negative: true
                boost: 1
            _source:
              includes:
              - userId
              - progress
              - enrolledDate
              - batchId
              - dateTime
              excludes: []
            aggs:
              status:
                terms:
                  field: status.raw
                  include:
                  - 1
                  - 2
                  - review
                aggs:
                  updated_on:
                    date_histogram:
                      field: lastUpdatedOn
                      interval: 1d
                      format: yyyy-MM-dd
    required:
    - id
    - ts
    - params
    - request
  Request13:
    title: Request13
    example:
      entityName: announcement
      rawQuery:
        from: 0
        size: 250
        query:
          bool:
            must:
            - term:
                batchId.raw:
                  value: jkwf6t3r083fp4h
                  boost: 1
            disable_coord: false
            adjust_pure_negative: true
            boost: 1
        _source:
          includes:
          - userId
          - progress
          - enrolledDate
          - batchId
          - dateTime
          excludes: []
        aggs:
          status:
            terms:
              field: status.raw
              include:
              - 1
              - 2
              - review
            aggs:
              updated_on:
                date_histogram:
                  field: lastUpdatedOn
                  interval: 1d
                  format: yyyy-MM-dd
    type: object
    properties:
      entityName:
        description: ''
        example: announcement
        type: string
      rawQuery:
        $ref: '#/definitions/RawQuery'
        example:
          from: 0
          size: 250
          query:
            bool:
              must:
              - term:
                  batchId.raw:
                    value: jkwf6t3r083fp4h
                    boost: 1
              disable_coord: false
              adjust_pure_negative: true
              boost: 1
          _source:
            includes:
            - userId
            - progress
            - enrolledDate
            - batchId
            - dateTime
            excludes: []
          aggs:
            status:
              terms:
                field: status.raw
                include:
                - 1
                - 2
                - review
              aggs:
                updated_on:
                  date_histogram:
                    field: lastUpdatedOn
                    interval: 1d
                    format: yyyy-MM-dd
    required:
    - entityName
    - rawQuery
  RawQuery:
    title: RawQuery
    example:
      from: 0
      size: 250
      query:
        bool:
          must:
          - term:
              batchId.raw:
                value: jkwf6t3r083fp4h
                boost: 1
          disable_coord: false
          adjust_pure_negative: true
          boost: 1
      _source:
        includes:
        - userId
        - progress
        - enrolledDate
        - batchId
        - dateTime
        excludes: []
      aggs:
        status:
          terms:
            field: status.raw
            include:
            - 1
            - 2
            - review
          aggs:
            updated_on:
              date_histogram:
                field: lastUpdatedOn
                interval: 1d
                format: yyyy-MM-dd
    type: object
    properties:
      from:
        description: ''
        example: 0
        type: integer
        format: int32
      size:
        description: ''
        example: 250
        type: integer
        format: int32
      query:
        $ref: '#/definitions/Query'
        example:
          bool:
            must:
            - term:
                batchId.raw:
                  value: jkwf6t3r083fp4h
                  boost: 1
            disable_coord: false
            adjust_pure_negative: true
            boost: 1
      _source:
        $ref: '#/definitions/Source'
        example:
          includes:
          - userId
          - progress
          - enrolledDate
          - batchId
          - dateTime
          excludes: []
      aggs:
        $ref: '#/definitions/Aggs'
        example:
          status:
            terms:
              field: status.raw
              include:
              - 1
              - 2
              - review
            aggs:
              updated_on:
                date_histogram:
                  field: lastUpdatedOn
                  interval: 1d
                  format: yyyy-MM-dd
    required:
    - from
    - size
    - query
    - _source
    - aggs
  Query:
    title: Query
    example:
      bool:
        must:
        - term:
            batchId.raw:
              value: jkwf6t3r083fp4h
              boost: 1
        disable_coord: false
        adjust_pure_negative: true
        boost: 1
    type: object
    properties:
      bool:
        $ref: '#/definitions/Bool'
        example:
          must:
          - term:
              batchId.raw:
                value: jkwf6t3r083fp4h
                boost: 1
          disable_coord: false
          adjust_pure_negative: true
          boost: 1
    required:
    - bool
  Bool:
    title: Bool
    example:
      must:
      - term:
          batchId.raw:
            value: jkwf6t3r083fp4h
            boost: 1
      disable_coord: false
      adjust_pure_negative: true
      boost: 1
    type: object
    properties:
      must:
        description: ''
        example:
        - term:
            batchId.raw:
              value: jkwf6t3r083fp4h
              boost: 1
        type: array
        items:
          $ref: '#/definitions/Must'
      disable_coord:
        description: ''
        example: false
        type: boolean
      adjust_pure_negative:
        description: ''
        example: true
        type: boolean
      boost:
        description: ''
        example: 1
        type: integer
        format: int32
    required:
    - must
    - disable_coord
    - adjust_pure_negative
    - boost
  Must:
    title: Must
    example:
      term:
        batchId.raw:
          value: jkwf6t3r083fp4h
          boost: 1
    type: object
    properties:
      term:
        $ref: '#/definitions/Term'
        example:
          batchId.raw:
            value: jkwf6t3r083fp4h
            boost: 1
    required:
    - term
  Term:
    title: Term
    example:
      batchId.raw:
        value: jkwf6t3r083fp4h
        boost: 1
    type: object
    properties:
      batchId.raw:
        $ref: '#/definitions/BatchIdRaw'
        example:
          value: jkwf6t3r083fp4h
          boost: 1
    required:
    - batchId.raw
  BatchIdRaw:
    title: BatchIdRaw
    example:
      value: jkwf6t3r083fp4h
      boost: 1
    type: object
    properties:
      value:
        description: ''
        example: jkwf6t3r083fp4h
        type: string
      boost:
        description: ''
        example: 1
        type: integer
        format: int32
    required:
    - value
    - boost
  Source:
    title: Source
    example:
      includes:
      - userId
      - progress
      - enrolledDate
      - batchId
      - dateTime
      excludes: []
    type: object
    properties:
      includes:
        description: ''
        example:
        - userId
        - progress
        - enrolledDate
        - batchId
        - dateTime
        type: array
        items:
          type: string
      excludes:
        description: ''
        example: []
        type: array
        items:
          type: string
    required:
    - includes
    - excludes
  Aggs:
    title: Aggs
    example:
      status:
        terms:
          field: status.raw
          include:
          - 1
          - 2
          - review
        aggs:
          updated_on:
            date_histogram:
              field: lastUpdatedOn
              interval: 1d
              format: yyyy-MM-dd
    type: object
    properties:
      status:
        $ref: '#/definitions/Status'
        example:
          terms:
            field: status.raw
            include:
            - 1
            - 2
            - review
          aggs:
            updated_on:
              date_histogram:
                field: lastUpdatedOn
                interval: 1d
                format: yyyy-MM-dd
    required:
    - status
  Status:
    title: Status
    example:
      terms:
        field: status.raw
        include:
        - 1
        - 2
        - review
      aggs:
        updated_on:
          date_histogram:
            field: lastUpdatedOn
            interval: 1d
            format: yyyy-MM-dd
    type: object
    properties:
      terms:
        $ref: '#/definitions/Terms'
        example:
          field: status.raw
          include:
          - 1
          - 2
          - review
      aggs:
        $ref: '#/definitions/Aggs24'
        example:
          updated_on:
            date_histogram:
              field: lastUpdatedOn
              interval: 1d
              format: yyyy-MM-dd
    required:
    - terms
    - aggs
  Terms:
    title: Terms
    example:
      field: status.raw
      include:
      - 1
      - 2
      - review
    type: object
    properties:
      field:
        description: ''
        example: status.raw
        type: string
      include:
        description: ''
        example:
        - 1
        - 2
        - review
        type: array
        items:
          type: string
    required:
    - field
    - include
  Aggs24:
    title: Aggs24
    example:
      updated_on:
        date_histogram:
          field: lastUpdatedOn
          interval: 1d
          format: yyyy-MM-dd
    type: object
    properties:
      updated_on:
        $ref: '#/definitions/UpdatedOn'
        example:
          date_histogram:
            field: lastUpdatedOn
            interval: 1d
            format: yyyy-MM-dd
    required:
    - updated_on
  UpdatedOn:
    title: UpdatedOn
    example:
      date_histogram:
        field: lastUpdatedOn
        interval: 1d
        format: yyyy-MM-dd
    type: object
    properties:
      date_histogram:
        $ref: '#/definitions/DateHistogram'
        example:
          field: lastUpdatedOn
          interval: 1d
          format: yyyy-MM-dd
    required:
    - date_histogram
  DateHistogram:
    title: DateHistogram
    example:
      field: lastUpdatedOn
      interval: 1d
      format: yyyy-MM-dd
    type: object
    properties:
      field:
        description: ''
        example: lastUpdatedOn
        type: string
      interval:
        description: ''
        example: 1d
        type: string
      format:
        description: ''
        example: yyyy-MM-dd
        type: string
    required:
    - field
    - interval
    - format
  DeleteObjectrequest:
    title: Delete ObjectRequest
    example:
      id: ''
      ts: ''
      params: {}
      request:
        entityName: announcement
        indexed: announcement
        id: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
    type: object
    properties:
      id:
        description: ''
        type: string
      ts:
        description: ''
        type: string
      params:
        description: ''
        example: {}
        type: object
      request:
        $ref: '#/definitions/Request28'
        example:
          entityName: announcement
          indexed: announcement
          id: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
    required:
    - id
    - ts
    - params
    - request
  Request28:
    title: Request28
    example:
      entityName: announcement
      indexed: announcement
      id: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
    type: object
    properties:
      entityName:
        description: ''
        example: announcement
        type: string
      indexed:
        description: ''
        example: announcement
        type: string
      id:
        description: ''
        example: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
        type: string
    required:
    - entityName
    - indexed
    - id
  SearchObjectrequest:
    title: Search ObjectRequest
    example:
      id: ''
      ts: ''
      params: {}
      request:
        query: ORG_TYPE
        entityName: org_type
        filters:
          id: 98765432110
        offset: 0
        limit: 5
    type: object
    properties:
      id:
        description: ''
        type: string
      ts:
        description: ''
        type: string
      params:
        description: ''
        example: {}
        type: object
      request:
        $ref: '#/definitions/Request30'
        example:
          query: ORG_TYPE
          entityName: org_type
          filters:
            id: 98765432110
          offset: 0
          limit: 5
    required:
    - id
    - ts
    - params
    - request
  Request30:
    title: Request30
    example:
      query: ORG_TYPE
      entityName: org_type
      filters:
        id: 98765432110
      offset: 0
      limit: 5
    type: object
    properties:
      query:
        description: ''
        example: ORG_TYPE
        type: string
      entityName:
        description: ''
        example: org_type
        type: string
      filters:
        $ref: '#/definitions/Filters'
        example:
          id: 98765432110
      offset:
        description: ''
        example: 0
        type: integer
        format: int32
      limit:
        description: ''
        example: 5
        type: integer
        format: int32
    required:
    - query
    - entityName
    - filters
    - offset
    - limit
  Filters:
    title: Filters
    example:
      id: 98765432110
    type: object
    properties:
      id:
        description: ''
        example: 98765432110
        type: string
    required:
    - id
