swagger: '2.0'
info:
  version: '1.0'
  title: pageApi copy
  description: 'TODO: Add Description'
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: example.com
basePath: /v1/page
securityDefinitions:
  auth:
    type: oauth2
    flow: implicit
    authorizationUrl: http://example.com/v1/page
    scopes: {}
    x-skip-client-authentication: false
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /all/settings:
    get:
      description: ''
      summary: get All Page Settings
      operationId: AllSettingsGet
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: X-msgid
        in: header
        required: true
        type: string
        description: ''
      - name: ts
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      - name: x-authenticated-user-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: GET
          uri: /all/settings
          headers:
            Content-Type: application/json
            X-msgid: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
            ts: 2017-05-25 10:18:56:578+0530
            Authorization: Bearer {{api-key}}
            x-authenticated-user-token: '{{user-token}}'
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: get All Page Settings
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /Resource:
    get:
      description: ''
      summary: get particular page Settings
      operationId: ResourceGet
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: X-msgid
        in: header
        required: true
        type: string
        description: ''
      - name: ts
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      - name: x-authenticated-user-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: GET
          uri: /Resource
          headers:
            Content-Type: application/json
            X-msgid: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
            ts: 2017-05-25 10:18:56:578+0530
            Authorization: Bearer {{api-key}}
            x-authenticated-user-token: '{{user-token}}'
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: get particular page Settings
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /section/all/settings:
    get:
      description: ''
      summary: get all section settings
      operationId: SectionAllSettingsGet
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: X-msgid
        in: header
        required: true
        type: string
        description: ''
      - name: ts
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      - name: x-authenticated-user-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: GET
          uri: /section/all/settings
          headers:
            Content-Type: application/json
            X-msgid: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
            ts: 2017-05-25 10:18:56:578+0530
            Authorization: Bearer {{api-key}}
            x-authenticated-user-token: '{{user-token}}'
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: get all section settings
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /create:
    post:
      description: ''
      summary: create page
      operationId: CreatePost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/CreatePagerequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: X-msgid
        in: header
        required: true
        type: string
        description: ''
      - name: ts
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      - name: x-authenticated-user-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: POST
          uri: /create
          headers:
            Content-Type: application/json
            X-msgid: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
            ts: 2017-05-25 10:18:56:578+0530
            Authorization: Bearer {{api-key}}
            x-authenticated-user-token: '{{user-token}}'
          body: "{\r\n\"id\":\"unique API ID\",\r\n\"ts\":\"2013/10/15 16:16:39\",\r\n\"params\": { },\r\n \"request\":{\r\n        \"name\":\"Resources\",\r\n        \"portalMap\":[\r\n           {\r\n            \"id\":\"01228383082462412826\",\r\n            \"index\":1,\r\n            \"group\":1\r\n            \r\n          },\r\n           {\r\n            \"id\":\"01228383384379392023\",\r\n             \"index\":1,\r\n            \"group\":2\r\n          }\r\n        ],\r\n        \"appMap\":[\r\n          {\r\n            \"id\":\"01228383082462412826\",\r\n             \"index\":1,\r\n            \"group\":1\r\n          },\r\n           {\r\n            \"id\":\"01228383384379392023\",\r\n             \"index\":1,\r\n            \"group\":2\r\n          }\r\n          ]\r\n        \r\n      }\r\n   }"
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: create page
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /section/create:
    post:
      description: ''
      summary: create page section
      operationId: SectionCreatePost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/CreatePageSectionrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: X-msgid
        in: header
        required: true
        type: string
        description: ''
      - name: ts
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      - name: x-authenticated-user-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: POST
          uri: /section/create
          headers:
            Content-Type: application/json
            X-msgid: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
            ts: 2017-05-25 10:18:56:578+0530
            Authorization: Bearer {{api-key}}
            x-authenticated-user-token: '{{user-token}}'
          body: >-
            {

            "id":"unique API ID",

            "ts":"2013/10/15 16:16:39",

            "params": { },

            "request":{

             "name":"Recommended TextBook",

             "searchQuery":{"request": {

                 "query":"",

                 "filters":

                 {"language":["English"],"contentType":["TextBook"]},"limit":10,"sort_by":{"lastUpdatedOn":"desc"}}},

             "sectionDataType" :"course",

             "display":{"name":{"en":"popular story","hi":"????????"}}

                    }

              }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: create page section
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /section/update:
    patch:
      description: ''
      summary: update page section info
      operationId: SectionUpdatePatch
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/UpdatePageSectionInforequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: X-msgid
        in: header
        required: true
        type: string
        description: ''
      - name: ts
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      - name: x-authenticated-user-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: PATCH
          uri: /section/update
          headers:
            Content-Type: application/json
            X-msgid: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
            ts: 2017-05-25 10:18:56:578+0530
            Authorization: Bearer {{api-key}}
            x-authenticated-user-token: '{{user-token}}'
          body: >-
            {

            "id":"unique API ID",

            "ts":"2013/10/15 16:16:39",

            "params": { },

            "request":{

              "id":"0122662435116892160",

             "name":"Popular Course",

             "searchQuery":{"request": { "query": "","filters":{"objectType": ["Content"],"mimeType": ["application/vnd.ekstep.html-archive"],"status": ["Draft", "Live"]},"offset": 0,"limit": 5 }},

             "sectionDataType" :"course",

             "display":{

                    "name":{

                            "en":"popular Course",

                            "hi":"????????"

                              }

                      }

                    }

              }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: update page section info
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /section/0122771215738306560:
    get:
      description: ''
      summary: get section details by id
      operationId: Section0122771215738306560Get
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: X-msgid
        in: header
        required: true
        type: string
        description: ''
      - name: ts
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      - name: x-authenticated-user-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: GET
          uri: /section/0122771215738306560
          headers:
            Content-Type: application/json
            X-msgid: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
            ts: 2017-05-25 10:18:56:578+0530
            Authorization: Bearer {{api-key}}
            x-authenticated-user-token: '{{user-token}}'
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: get section details by id
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /update:
    patch:
      description: ''
      summary: update page info
      operationId: UpdatePatch
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/UpdatePageInforequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: X-msgid
        in: header
        required: true
        type: string
        description: ''
      - name: ts
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      - name: x-authenticated-user-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: PATCH
          uri: /update
          headers:
            Content-Type: application/json
            X-msgid: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
            ts: 2017-05-25 10:18:56:578+0530
            Authorization: Bearer {{api-key}}
            x-authenticated-user-token: '{{user-token}}'
          body: "{\r\n\"id\":\"unique API ID\",\r\n\"ts\":\"2013/10/15 16:16:39\",\r\n\"params\": { },\r\n \"request\":{\r\n        \"name\":\"Resourcessss\",\r\n        \"id\":\"01228394137835929612\",\r\n        \"portalMap\":[\r\n           {\r\n            \"id\":\"01228383082462412826\",\r\n            \"index\":1,\r\n            \"group\":1\r\n            \r\n          },\r\n           {\r\n            \"id\":\"01228383384379392023\",\r\n             \"index\":1,\r\n            \"group\":2\r\n          }\r\n        ],\r\n        \"appMap\":[\r\n          {\r\n            \"id\":\"01228383082462412826\",\r\n             \"index\":1,\r\n            \"group\":1\r\n          },\r\n           {\r\n            \"id\":\"01228383384379392023\",\r\n             \"index\":1,\r\n            \"group\":2\r\n          }\r\n          ]\r\n        \r\n      }\r\n   }"
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: update page info
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /assemble:
    post:
      description: ''
      summary: get page data / assemble
      operationId: AssemblePost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/GetPageData~1Assemblerequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: X-msgid
        in: header
        required: true
        type: string
        description: ''
      - name: ts
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      - name: x-authenticated-user-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: POST
          uri: /assemble
          headers:
            Content-Type: application/json
            X-msgid: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
            ts: 2017-05-25 10:18:56:578+0530
            Authorization: Bearer {{api-key}}
            x-authenticated-user-token: '{{user-token}}'
          body: "{\r\n\"id\":\"unique API ID\",\r\n\"ts\":\"2013/10/15 16:16:39\",\r\n\"params\": { },\r\n \"request\":{\r\n         \"source\":\"web\",\r\n         \"name\":\"page\",\r\n         \"filters\":{\r\n                 \"objectType\": [\"Content\"]\r\n                \r\n         }\r\n      }\r\n   }"
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: get page data / assemble
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
definitions:
  CreatePagerequest:
    title: create pageRequest
    example:
      id: unique API ID
      ts: 2013/10/15 16:16:39
      params: {}
      request:
        name: Resources
        portalMap:
        - id: 01228383082462412826
          index: 1
          group: 1
        - id: 01228383384379392023
          index: 1
          group: 2
        appMap:
        - id: 01228383082462412826
          index: 1
          group: 1
        - id: 01228383384379392023
          index: 1
          group: 2
    type: object
    properties:
      id:
        description: ''
        example: unique API ID
        type: string
      ts:
        description: ''
        example: 2013/10/15 16:16:39
        type: string
      params:
        description: ''
        example: {}
        type: object
      request:
        $ref: '#/definitions/Request'
        example:
          name: Resources
          portalMap:
          - id: 01228383082462412826
            index: 1
            group: 1
          - id: 01228383384379392023
            index: 1
            group: 2
          appMap:
          - id: 01228383082462412826
            index: 1
            group: 1
          - id: 01228383384379392023
            index: 1
            group: 2
    required:
    - id
    - ts
    - params
    - request
  Request:
    title: Request
    example:
      name: Resources
      portalMap:
      - id: 01228383082462412826
        index: 1
        group: 1
      - id: 01228383384379392023
        index: 1
        group: 2
      appMap:
      - id: 01228383082462412826
        index: 1
        group: 1
      - id: 01228383384379392023
        index: 1
        group: 2
    type: object
    properties:
      name:
        description: ''
        example: Resources
        type: string
      portalMap:
        description: ''
        example:
        - id: 01228383082462412826
          index: 1
          group: 1
        - id: 01228383384379392023
          index: 1
          group: 2
        type: array
        items:
          $ref: '#/definitions/PortalMap'
      appMap:
        description: ''
        example:
        - id: 01228383082462412826
          index: 1
          group: 1
        - id: 01228383384379392023
          index: 1
          group: 2
        type: array
        items:
          $ref: '#/definitions/AppMap'
    required:
    - name
    - portalMap
    - appMap
  PortalMap:
    title: PortalMap
    example:
      id: 01228383082462412826
      index: 1
      group: 1
    type: object
    properties:
      id:
        description: ''
        example: 01228383082462412826
        type: string
      index:
        description: ''
        example: 1
        type: integer
        format: int32
      group:
        description: ''
        example: 1
        type: integer
        format: int32
    required:
    - id
    - index
    - group
  AppMap:
    title: AppMap
    example:
      id: 01228383082462412826
      index: 1
      group: 1
    type: object
    properties:
      id:
        description: ''
        example: 01228383082462412826
        type: string
      index:
        description: ''
        example: 1
        type: integer
        format: int32
      group:
        description: ''
        example: 1
        type: integer
        format: int32
    required:
    - id
    - index
    - group
  CreatePageSectionrequest:
    title: create page sectionRequest
    example:
      id: unique API ID
      ts: 2013/10/15 16:16:39
      params: {}
      request:
        name: Recommended TextBook
        searchQuery:
          request:
            query: ''
            filters:
              language:
              - English
              contentType:
              - TextBook
            limit: 10
            sort_by:
              lastUpdatedOn: desc
        sectionDataType: course
        display:
          name:
            en: popular story
            hi: ????????
    type: object
    properties:
      id:
        description: ''
        example: unique API ID
        type: string
      ts:
        description: ''
        example: 2013/10/15 16:16:39
        type: string
      params:
        description: ''
        example: {}
        type: object
      request:
        $ref: '#/definitions/Request5'
        example:
          name: Recommended TextBook
          searchQuery:
            request:
              query: ''
              filters:
                language:
                - English
                contentType:
                - TextBook
              limit: 10
              sort_by:
                lastUpdatedOn: desc
          sectionDataType: course
          display:
            name:
              en: popular story
              hi: ????????
    required:
    - id
    - ts
    - params
    - request
  Request5:
    title: Request5
    example:
      name: Recommended TextBook
      searchQuery:
        request:
          query: ''
          filters:
            language:
            - English
            contentType:
            - TextBook
          limit: 10
          sort_by:
            lastUpdatedOn: desc
      sectionDataType: course
      display:
        name:
          en: popular story
          hi: ????????
    type: object
    properties:
      name:
        description: ''
        example: Recommended TextBook
        type: string
      searchQuery:
        $ref: '#/definitions/SearchQuery'
        example:
          request:
            query: ''
            filters:
              language:
              - English
              contentType:
              - TextBook
            limit: 10
            sort_by:
              lastUpdatedOn: desc
      sectionDataType:
        description: ''
        example: course
        type: string
      display:
        $ref: '#/definitions/Display'
        example:
          name:
            en: popular story
            hi: ????????
    required:
    - name
    - searchQuery
    - sectionDataType
    - display
  SearchQuery:
    title: SearchQuery
    example:
      request:
        query: ''
        filters:
          language:
          - English
          contentType:
          - TextBook
        limit: 10
        sort_by:
          lastUpdatedOn: desc
    type: object
    properties:
      request:
        $ref: '#/definitions/Request7'
        example:
          query: ''
          filters:
            language:
            - English
            contentType:
            - TextBook
          limit: 10
          sort_by:
            lastUpdatedOn: desc
    required:
    - request
  Request7:
    title: Request7
    example:
      query: ''
      filters:
        language:
        - English
        contentType:
        - TextBook
      limit: 10
      sort_by:
        lastUpdatedOn: desc
    type: object
    properties:
      query:
        description: ''
        type: string
      filters:
        $ref: '#/definitions/Filters'
        example:
          language:
          - English
          contentType:
          - TextBook
      limit:
        description: ''
        example: 10
        type: integer
        format: int32
      sort_by:
        $ref: '#/definitions/SortBy'
        example:
          lastUpdatedOn: desc
    required:
    - query
    - filters
    - limit
    - sort_by
  Filters:
    title: Filters
    example:
      language:
      - English
      contentType:
      - TextBook
    type: object
    properties:
      language:
        description: ''
        example:
        - English
        type: array
        items:
          type: string
      contentType:
        description: ''
        example:
        - TextBook
        type: array
        items:
          type: string
    required:
    - language
    - contentType
  SortBy:
    title: SortBy
    example:
      lastUpdatedOn: desc
    type: object
    properties:
      lastUpdatedOn:
        description: ''
        example: desc
        type: string
    required:
    - lastUpdatedOn
  Display:
    title: Display
    example:
      name:
        en: popular story
        hi: ????????
    type: object
    properties:
      name:
        $ref: '#/definitions/Name'
        example:
          en: popular story
          hi: ????????
    required:
    - name
  Name:
    title: Name
    example:
      en: popular story
      hi: ????????
    type: object
    properties:
      en:
        description: ''
        example: popular story
        type: string
      hi:
        description: ''
        example: ????????
        type: string
    required:
    - en
    - hi
  UpdatePageSectionInforequest:
    title: update page section infoRequest
    example:
      id: unique API ID
      ts: 2013/10/15 16:16:39
      params: {}
      request:
        id: 0122662435116892160
        name: Popular Course
        searchQuery:
          request:
            query: ''
            filters:
              objectType:
              - Content
              mimeType:
              - application/vnd.ekstep.html-archive
              status:
              - Draft
              - Live
            offset: 0
            limit: 5
        sectionDataType: course
        display:
          name:
            en: popular Course
            hi: ????????
    type: object
    properties:
      id:
        description: ''
        example: unique API ID
        type: string
      ts:
        description: ''
        example: 2013/10/15 16:16:39
        type: string
      params:
        description: ''
        example: {}
        type: object
      request:
        $ref: '#/definitions/Request13'
        example:
          id: 0122662435116892160
          name: Popular Course
          searchQuery:
            request:
              query: ''
              filters:
                objectType:
                - Content
                mimeType:
                - application/vnd.ekstep.html-archive
                status:
                - Draft
                - Live
              offset: 0
              limit: 5
          sectionDataType: course
          display:
            name:
              en: popular Course
              hi: ????????
    required:
    - id
    - ts
    - params
    - request
  Request13:
    title: Request13
    example:
      id: 0122662435116892160
      name: Popular Course
      searchQuery:
        request:
          query: ''
          filters:
            objectType:
            - Content
            mimeType:
            - application/vnd.ekstep.html-archive
            status:
            - Draft
            - Live
          offset: 0
          limit: 5
      sectionDataType: course
      display:
        name:
          en: popular Course
          hi: ????????
    type: object
    properties:
      id:
        description: ''
        example: 0122662435116892160
        type: string
      name:
        description: ''
        example: Popular Course
        type: string
      searchQuery:
        $ref: '#/definitions/SearchQuery14'
        example:
          request:
            query: ''
            filters:
              objectType:
              - Content
              mimeType:
              - application/vnd.ekstep.html-archive
              status:
              - Draft
              - Live
            offset: 0
            limit: 5
      sectionDataType:
        description: ''
        example: course
        type: string
      display:
        $ref: '#/definitions/Display'
        example:
          name:
            en: popular Course
            hi: ????????
    required:
    - id
    - name
    - searchQuery
    - sectionDataType
    - display
  SearchQuery14:
    title: SearchQuery14
    example:
      request:
        query: ''
        filters:
          objectType:
          - Content
          mimeType:
          - application/vnd.ekstep.html-archive
          status:
          - Draft
          - Live
        offset: 0
        limit: 5
    type: object
    properties:
      request:
        $ref: '#/definitions/Request15'
        example:
          query: ''
          filters:
            objectType:
            - Content
            mimeType:
            - application/vnd.ekstep.html-archive
            status:
            - Draft
            - Live
          offset: 0
          limit: 5
    required:
    - request
  Request15:
    title: Request15
    example:
      query: ''
      filters:
        objectType:
        - Content
        mimeType:
        - application/vnd.ekstep.html-archive
        status:
        - Draft
        - Live
      offset: 0
      limit: 5
    type: object
    properties:
      query:
        description: ''
        type: string
      filters:
        $ref: '#/definitions/Filters16'
        example:
          objectType:
          - Content
          mimeType:
          - application/vnd.ekstep.html-archive
          status:
          - Draft
          - Live
      offset:
        description: ''
        example: 0
        type: integer
        format: int32
      limit:
        description: ''
        example: 5
        type: integer
        format: int32
    required:
    - query
    - filters
    - offset
    - limit
  Filters16:
    title: Filters16
    example:
      objectType:
      - Content
      mimeType:
      - application/vnd.ekstep.html-archive
      status:
      - Draft
      - Live
    type: object
    properties:
      objectType:
        description: ''
        example:
        - Content
        type: array
        items:
          type: string
      mimeType:
        description: ''
        example:
        - application/vnd.ekstep.html-archive
        type: array
        items:
          type: string
      status:
        description: ''
        example:
        - Draft
        - Live
        type: array
        items:
          type: string
    required:
    - objectType
    - mimeType
    - status
  UpdatePageInforequest:
    title: update page infoRequest
    example:
      id: unique API ID
      ts: 2013/10/15 16:16:39
      params: {}
      request:
        name: Resourcessss
        id: 01228394137835929612
        portalMap:
        - id: 01228383082462412826
          index: 1
          group: 1
        - id: 01228383384379392023
          index: 1
          group: 2
        appMap:
        - id: 01228383082462412826
          index: 1
          group: 1
        - id: 01228383384379392023
          index: 1
          group: 2
    type: object
    properties:
      id:
        description: ''
        example: unique API ID
        type: string
      ts:
        description: ''
        example: 2013/10/15 16:16:39
        type: string
      params:
        description: ''
        example: {}
        type: object
      request:
        $ref: '#/definitions/Request20'
        example:
          name: Resourcessss
          id: 01228394137835929612
          portalMap:
          - id: 01228383082462412826
            index: 1
            group: 1
          - id: 01228383384379392023
            index: 1
            group: 2
          appMap:
          - id: 01228383082462412826
            index: 1
            group: 1
          - id: 01228383384379392023
            index: 1
            group: 2
    required:
    - id
    - ts
    - params
    - request
  Request20:
    title: Request20
    example:
      name: Resourcessss
      id: 01228394137835929612
      portalMap:
      - id: 01228383082462412826
        index: 1
        group: 1
      - id: 01228383384379392023
        index: 1
        group: 2
      appMap:
      - id: 01228383082462412826
        index: 1
        group: 1
      - id: 01228383384379392023
        index: 1
        group: 2
    type: object
    properties:
      name:
        description: ''
        example: Resourcessss
        type: string
      id:
        description: ''
        example: 01228394137835929612
        type: string
      portalMap:
        description: ''
        example:
        - id: 01228383082462412826
          index: 1
          group: 1
        - id: 01228383384379392023
          index: 1
          group: 2
        type: array
        items:
          $ref: '#/definitions/PortalMap'
      appMap:
        description: ''
        example:
        - id: 01228383082462412826
          index: 1
          group: 1
        - id: 01228383384379392023
          index: 1
          group: 2
        type: array
        items:
          $ref: '#/definitions/AppMap'
    required:
    - name
    - id
    - portalMap
    - appMap
  GetPageData/Assemblerequest:
    title: get page data / assembleRequest
    example:
      id: unique API ID
      ts: 2013/10/15 16:16:39
      params: {}
      request:
        source: web
        name: page
        filters:
          objectType:
          - Content
    type: object
    properties:
      id:
        description: ''
        example: unique API ID
        type: string
      ts:
        description: ''
        example: 2013/10/15 16:16:39
        type: string
      params:
        description: ''
        example: {}
        type: object
      request:
        $ref: '#/definitions/Request24'
        example:
          source: web
          name: page
          filters:
            objectType:
            - Content
    required:
    - id
    - ts
    - params
    - request
  Request24:
    title: Request24
    example:
      source: web
      name: page
      filters:
        objectType:
        - Content
    type: object
    properties:
      source:
        description: ''
        example: web
        type: string
      name:
        description: ''
        example: page
        type: string
      filters:
        $ref: '#/definitions/Filters25'
        example:
          objectType:
          - Content
    required:
    - source
    - name
    - filters
  Filters25:
    title: Filters25
    example:
      objectType:
      - Content
    type: object
    properties:
      objectType:
        description: ''
        example:
        - Content
        type: array
        items:
          type: string
    required:
    - objectType
